package me.fang.kosh.exceptions

/**
 * Исключение, которое выбрасывает команда `exit` при выполнении
 */
internal class ExitCalledException : RuntimeException()
